---
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4  # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-pytest-style
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        language_version: python3
        exclude: tests/
  - repo: https://github.com/rubik/xenon.git
    rev: master
    hooks:
      - id: xenon
        args: [-bB, -mB, -aA]
        exclude: '^.*/tests/.*$'
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-gitlab-ci
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.0.1
    hooks:
      - id: pip-compile
        args: [--no-emit-index-url, --no-emit-trusted-host]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
        args: [requirements.txt]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.0
    hooks:
      - id: yamllint
